let $ = s => document.querySelector(s);
let t = $("#fullscr-toggler");
let b = $("#browser");
let d = document.documentElement;
let p = v => d.toggleAttribute("customtitlebar", v);
let e = (n, e, a, c) => n.addEventListener("mouse"+e, e => e.target == n && a(e), c);
t.style.setProperty("display", "block", "important");
e(t, "enter", e => p(0));
e(b, "enter", e => p(1));
e(d, "leave", e => e.clientY < (outerWidth - d.clientWidth) / 2 + 2 && p(0), 1);
p(0);
